name: firebase_database
description: Flutter plugin for Firebase Database, a cloud-hosted NoSQL database
  with realtime data syncing across Android and iOS clients, and offline access.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_database
version: 6.1.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.0
dev_dependencies:
  firebase_core_platform_interface: ^4.0.0
  pedantic: ^1.8.0
  test: any
  mockito: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.database
        pluginClass: FirebaseDatabasePlugin
      ios:
        pluginClass: FLTFirebaseDatabasePlugin
      macos:
        pluginClass: FLTFirebaseDatabasePlugin
